//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Project.Models
{
    using Portfolio_Project.Models.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioEntities : DbContext
    {
        public PortfolioEntities()
            : base("name=PortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblContact> TblContact { get; set; }
        public DbSet<TblDepartment> TblDepartment { get; set; }
        public DbSet<TblEmployee> TblEmployee { get; set; }
        public DbSet<TblFeature> TblFeature { get; set; }
        public DbSet<TblMessage> TblMessage { get; set; }
        public DbSet<TblProject> TblProject { get; set; }
        public DbSet<TblReference> TblReference { get; set; }
        public DbSet<TblResume> TblResume { get; set; }
        public DbSet<TblService> TblService { get; set; }
        public DbSet<TblVideo> TblVideo { get; set; }
    }
}
